### PR TITLE
Alpha datavisualisation

### PR DESCRIPTION
**Pull request by Wagnerp**
* Data visualisation module

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Are there going to be examples on how to use these updates (Especially the animation code base)

**Comment by Wagnerp** [comment]
> Are there going to be examples on how to use these updates (Especially the animation code base)

Yes, though I'm trying to get it to build first.

**Comment by Wagnerp** [comment]
> These files need BSD headers

Going to use the 'License Header' extension to do this.

**Comment by Wagnerp** [comment]
Some minor things may need to be looked at later on.

**Comment by Smurf-IV** [comment]
Is this ready now ?

**Comment by Wagnerp** [comment]
Yes it is

**Pull request merged**
