### PR TITLE
- Alpha messagebox and toasts

### PR DESCRIPTION
**Pull request by Wagnerp**
* More options

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be merged?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Can this be merged?

No, Still has pending comments that need to be resolved.

**Comment by Smurf-IV** [comment]
> > > @Smurf-IV Can this be merged?
> > 
> > 
> > No, Still has pending comments that need to be resolved.
> 
> I'm stumped as to why I can't see the comments?

Scroll up when after using the link to "View in Github" in the email message:
image

**Comment by Wagnerp** [comment]
Comments have been addressed

**Pull request merged**
