### PR TITLE
- Sort out the namespaces and public access to relevant classes

### LINKED ISSUE #210: [Bug]: Nameof `TreeGridView` workspace needs sorting
**Describe the bug**
`namespace Krypton.Toolkit.Suite.Extended.Tree.Grid.View`

Should be 

`namespace Krypton.Toolkit.Suite.Extended.TreeGridView`

### LINKED ISSUE #214: [Bug]: `TreeGridView` _Probably_ only works with a DataSource
**Describe the bug**
As part of the investigation of #210
I have not found a "Neat" way of getting the Tree view to populate as tree - only as a Grid with base level rows
(To be expected really as that is the base class)

**To Reproduce**
Something like this would be nice:
``` c#
            var row = gdView.Rows.Add(1, @"Name", @"CreatedUTC", @"ReveiwState", @"UserID");
            var parent = gdView.GetNodeForRow(row);
            row = gdView.Rows.Add(1, @"Child Name", @"Child CreatedUTC", @"Child ReveiwState", @"Child UserID");
            var child = gdView.GetNodeForRow(row);
            parent.Nodes.Add(child);
```
But that just throws an exception, and even changing it to 
``` c#
            var row = gdView.Rows.Add(1, @"Name", @"CreatedUTC", @"ReveiwState", @"UserID");
            var parent = gdView.GetNodeForRow(row);
            parent.Nodes.Add(1, @"Child Name", @"Child CreatedUTC", @"Child ReveiwState", @"Child UserID");
```
throws the same exception.

The code does not make sense if a DataSource is not passed in on initialisation 

**Expected behavior**
To progmattically create the heirachy based on delay opening etc.

**Update:**
I have found the original source with examples on how to use this:
https://docs.microsoft.com/en-us/archive/blogs/markrideout/new-link-for-treegridview

### PR DESCRIPTION
**Pull request by Smurf-IV**
- Sort out the namespaces and public access to relevant classes
- Change the Directory Name to `TreeGridView`
- Add Example Code to demonstrate `DataSource` and `Progmatic` creation
- Remove some compile warnings and messages
- Update a few Readme's

Closes #210
Closes #214

### CODE REVIEW

**Review by Wagnerp — APPROVED** [review]

**Comment by Wagnerp** [comment]
@Smurf-IV Will remove conflicting files

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Will remove conflicting files

You will, Or I will ?

And why do I have conflicting files, If I got Fresh branch yesterday morning ??

**Comment by Wagnerp** [comment]
> > @Smurf-IV Will remove conflicting files
> 
> You will, Or I will ?
> 
> And why do I have conflicting files, If I got Fresh branch yesterday morning ??

I will, but I'm in the process of completely rebuilding the `build.proj` file at the moment.

**Comment by Smurf-IV** [comment]
> 
> 
> > @Smurf-IV Will remove conflicting files
> 
> You will, Or I will ?
> 
> And why do I have conflicting files, If I got Fresh branch yesterday morning ??

Seems like It did not "Sync" fully, when getting fresh:
image

**Comment by Smurf-IV** [comment]
> 
> 
> > > @Smurf-IV Will remove conflicting files
> > 
> > 
> > You will, Or I will ?
> > And why do I have conflicting files, If I got Fresh branch yesterday morning ??
> 
> I will, but I'm in the process of completely rebuilding the `build.proj` file at the moment.

Thanks

**Comment by Wagnerp** [comment]
> > > > @Smurf-IV Will remove conflicting files
> > > 
> > > 
> > > You will, Or I will ?
> > > And why do I have conflicting files, If I got Fresh branch yesterday morning ??
> > 
> > 
> > I will, but I'm in the process of completely rebuilding the `build.proj` file at the moment.
> 
> Thanks

I may add the changes that you've made to the build I'm currently working on, then add it to a PR.

**Comment by Wagnerp** [comment]
@Smurf-IV Can this be closed, as I've merged it with PR #209?

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Can this be closed, as I've merged it with PR #209?

OK

**Pull request closed without merging**
