### PR TITLE
* Fix Bugs

### PR DESCRIPTION
**Pull request by Wagnerp**
Ongoing, do not merge until ready

### CODE REVIEW

**Comment by Wagnerp** [comment]
> Where is the image to demonstrate this ?
> And the updated readme file change to show it ?

Going to do it now, but it's going to show a simple `ArgumentNullException`

**Comment by Wagnerp** [comment]
> Can it show the stack trace as well ?
> And Internal Exceptions if they exist?

Yes it can, the following code may need refinement:

```cs
 /// <summary>Captures the exception.</summary>
        /// <param name="exception">The exception.</param>
        /// <param name="showMessageOnly">if set to <c>true</c> [show message only].</param>
        /// <param name="showStackTrace">if set to <c>true</c> [show stack trace].</param>
        /// <param name="showInnerException">if set to <c>true</c> [show inner exception].</param>
        /// <param name="showFullDetails">if set to <c>true</c> [show full details].</param>
        private void CaptureException(Exception exception, bool showMessageOnly = true,
                                      bool showStackTrace = false, bool showInnerException = false,
                                      bool showFullDetails = false)
        {
            if (showMessageOnly)
            {
                krtbException.Text = exception.Message;
            }
            else if (showStackTrace)
            {
                krtbException.Text = exception.StackTrace;
            }
            else if (showInnerException)
            {
                krtbException.Text = exception.InnerException.ToString();
            }

            if (showFullDetails)
            {
                StringBuilder builder = new StringBuilder();

                builder.Append($"{exception.Message}\n{exception.StackTrace}");

                krtbException.Text = builder.ToString();
            }
        }
```

**Comment by Smurf-IV** [comment]
Is this ready to be merged ?
If so, What is in the 2108.1 release for the Readme

**Comment by Wagnerp** [comment]
> Is this ready to be merged ?
> If so, What is in the 2108.1 release for the Readme

2108.1 is to fix possible `KryptonButton` text bugs that were in 2108 of the ST

**Pull request merged**
