### PR TITLE
Alpha messagebox

### PR DESCRIPTION
**Pull request by Wagnerp**
* Everything **but** the button locations work when using the optional checkbox

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV 

Other things to note are:-

- The back colour options for yes/no/cancel buttons don't work (not sure if this is locked)
- Button custom text options will throw an error _if_ the 'Help' button is shown
- The background of the checkbox is white at the moment for better debugging

**Comment by Smurf-IV** [comment]
Investigating today

**Comment by Smurf-IV** [comment]
VS 2019 crashed and now:
image

**Comment by Wagnerp** [comment]
> VS 2019 crashed and now: image

I haven't upgraded the `sln` to 2022 yet. Might put in another for 2022 specifically, same with std toolkit. My job for tomorrow when VS2022 RTMs

**Comment by Smurf-IV** [comment]
Does not work on Win 10:
image

**Comment by Wagnerp** [comment]
> Does not work on Win 10: image

Will need to be fixed in std toolkit, I'll get to fixing it today!

**Comment by Smurf-IV** [comment]
image

**Comment by Wagnerp** [comment]
I (think) the WINDOWSLOGO option is now fixed for Win 10 in the latest nightly

**Comment by Smurf-IV** [comment]
See comments and commit, I've given up for today, but at least it will be a guide for what to do.

**Comment by Wagnerp** [comment]
@Smurf-IV Is this ready to review?

**Comment by Smurf-IV** [comment]
No, I performed most of the work, and then gave it back to you to finish whatever you wanted to fix / implement in it next.

**Comment by Wagnerp** [comment]
I must have forgotten, I'll take a look when I finish the example for the DV module

**Comment by Wagnerp** [comment]
Progress so far

Animation

Note padding issues!

**Comment by Wagnerp** [comment]
https://github.com/Krypton-Suite/Standard-Toolkit/issues/607

**Comment by Wagnerp** [comment]
@Smurf-IV Closing, due to # of conflicts. Will re-implement on a fresh branch.

**Pull request closed without merging**
