### PR TITLE
Version next zip extractor

### PR DESCRIPTION
**Pull request by Wagnerp**

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Cannot "merge" due button being disabled:
image

**Comment by Wagnerp** [comment]
> Cannot "merge" due button being disabled:
> image

It's still work in progress. Hopefully should be merge ready by the end of today ;)

**Comment by Smurf-IV** [comment]
Whilst your at it, Can you remove some of the "Stale" branches (Currently running @ 25 is a bit much !)
image

**Comment by Wagnerp** [comment]
Now merge ready!

**Comment by Wagnerp** [comment]
> Whilst your at it, Can you remove some of the "Stale" branches (Currently running @ 25 is a bit much !)
> image

Done!

**Pull request merged**
